language: c
dist: bionic
os: linux
sudo: false

addons:
  apt:
    packages:
      - cmake
      - doxygen
      - graphviz
      - libc6-i386

before_install:
  - wget -c http://www.codesourcery.com/sgpp/lite/arm/portal/package4571/public/arm-none-linux-gnueabi/arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
  - tar xjf arm-2009q1-203-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2
  - export PATH="$PWD/arm-2009q1/bin:$PATH"
  - wget https://github.com/c4ev3/C4EV3.Toolchain/releases/download/C4EV3.Toolchain-2019.08.0/C4EV3.Toolchain-v2019.08.0-arm-c4ev3-linux-uclibceabi-gcc-8.2.1-uclibc-ng-1.0.31-binutils-2.31.1-kernel-2.6.33-rc4-sanitized_linux-amd64.tar.xz
  - tar xf C4EV3.Toolchain-v2019.08.0-arm-c4ev3-linux-uclibceabi-gcc-8.2.1-uclibc-ng-1.0.31-binutils-2.31.1-kernel-2.6.33-rc4-sanitized_linux-amd64.tar.xz
  - export PATH="$PWD/C4EV3.Toolchain-2019.08.0/arm-c4ev3-linux-uclibceabi/gcc-8.2.1-uclibc-ng-1.0.31-binutils-2.31.1-kernel-2.6.33-rc4-sanitized/bin:$PATH"

#
#before_script:
#  - make PREFIX=arm-none-linux-gnueabi- example
#  - nm -g libev3api.a | tee symbols.before
#  - grep EV3IsInitialized symbols.before || (echo "libev3api.a doesn't contain symbols! Aborting..." && false)
#

script:
  # build documentation
  - doxygen Doxyfile
  # build using glibc
  - mkdir -p build/glibc
  - cd build/glibc
  - cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../../CMake/codesourcery.cmake -DCMAKE_BUILD_TYPE=MinSizeRel
  - make all example.elf examples
  - cd ../..
  # build using uclibc
  - mkdir -p build/uclibc
  - cd build/uclibc
  - cmake ../.. -DCMAKE_TOOLCHAIN_FILE=../../CMake/c4ev3.cmake -DCMAKE_BUILD_TYPE=MinSizeRel
  - make all example.elf examples
  - cd ../..
  # prepare release
  - mkdir -p release/lib/glibc  && mv build/glibc/libev3api.a  release/lib/glibc/libev3api.a
  - mkdir -p release/lib/uclibc && mv build/uclibc/libev3api.a release/lib/uclibc/libev3api.a
  # prepare release zip
  - cp -r include release
  - mv release c4ev3-$TRAVIS_TAG && zip -r c4ev3.zip c4ev3-$TRAVIS_TAG

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: doxy_out/html
    github_token: $GH_REPO_TOKEN
    on:
      branch: master
  - provider: releases
    api_key: $GH_REPO_TOKEN
    file: "c4ev3.zip"
    skip_cleanup: true
    on:
      tags: true

after_script:
  - nm -g build/glibc/libev3api.a | tee symbols.after
  - grep InitEV3 symbols.after || (echo "libev3api.a from glibc toolchain doesn't contain symbols! Aborting..." && false)
  - nm -g build/glibc/example.elf
  - nm -g build/glibc/example.elf | grep InitEV3 || (echo "The InitEV3 constructor has not been included!! Aborting..." && false)

  - nm -g build/uclibc/libev3api.a | tee symbols.after
  - grep InitEV3 symbols.after || (echo "libev3api.a from uclibc toolchain doesn't contain symbols! Aborting..." && false)
  - nm -g build/uclibc/example.elf
  - nm -g build/uclibc/example.elf | grep InitEV3 || (echo "The InitEV3 constructor has not been included!! Aborting..." && false)
